Provide `ypkg variables` command

diff --git a/ypkg b/ypkg
--- a/ypkg
+++ b/ypkg
@@ -1081,7 +1081,7 @@ ypkg_command_list() {
         esac
         shift
     done
-    test $# -eq 0 || die "Too many arguments"
+    test $# -eq 0 || die "Usage: ypkg list [--]"
     ypkg_command_check $PACKAGES
 }
 
@@ -1305,6 +1305,57 @@ ypkg_command_reinstall() {
     ypkg_reinstall "$@"
 }
 
+ypkg_command_variables() {
+    local opt
+    opt="yes"
+    while test $# -gt 0 -a "$opt" = yes
+    do
+        case "$1" in
+            -- ) opt="no";;
+            -* ) die "Invalid option \"$1\"";;
+            *  ) break;;
+        esac
+        shift
+    done
+    test $# -eq 0 || die "Usage: ypkg variables [--]"
+    cat <<EOF
+# Common installation directory.
+PREFIX=$PREFIX
+
+# Where to install the sources.
+SRCDIR=$SRCDIR
+
+# Directory for customization scripts.
+SCRIPTDIR=$SCRIPTDIR
+
+# Directory for compiled libraries.
+LIBDIR=$LIBDIR
+
+# Directory for compiled packages.
+LIBEXECDIR=$LIBEXECDIR
+
+# Directory for executables.
+BINDIR=$BINDIR
+
+# Directory for architure-independent files.
+SHAREDIR=$SHAREDIR
+
+# Directory for manual pages.
+MANDIR=$MANDIR
+
+# Path to Yorick executable.
+YORICK_EXE=$YORICK_EXE
+
+# C compiler, compilation and link flags.
+CC=$CC
+CFLAGS=$CFLAGS
+LDFLAGS=$LDFLAGS
+
+# Use color for messages.
+YPKG_USE_COLORS=$YPKG_USE_COLORS
+EOF
+}
+
 ypkg_command_help() {
     cat <<EOF
 Usage: ypkg COMMAND [OPTIONS ...] [--] [PKG ...]
@@ -1375,6 +1426,10 @@ Low-level commands:
 
     forget [--] [PKG ...]
         Forget (that is, un-register) package(s).
+
+    variables [--]
+        List name and value of global variables which can be used in
+        customization scripts.
 EOF
 }
 
@@ -1390,7 +1445,7 @@ fi
 command="$1"
 shift
 case "$command" in
-    build|check|clone|forget|help|install|reinstall|list|register|update|upgrade)
+    build|check|clone|forget|help|install|reinstall|list|register|update|upgrade|variables)
         ypkg_command_$command "$@"
         ;;
     config|configure)
